source 'https://rubygems.org'

ruby "2.2.2"

gem 'dotenv',                   '~> 2.0.1'
gem 'sentry-raven',             '~> 0.13.1'
gem 'redis',                    '~> 3.2.1'
gem 'sidekiq',                  '~> 3.3.4'
gem 'bloomfilter-rb',           '~> 2.1.1'
gem 'aws-sdk',                  '~> 2.0.47'
gem 'mechanize',                '~> 2.7.3'
gem 'ruby-vips',                '~> 0.3.9'
gem 'fastimage',                '~> 1.7.0'
gem 'librato-metrics',          '~> 1.5.1'
gem 'yajl-ruby',                '~> 1.2.1'

group :test do
  gem 'rspec',                  '~> 3.2.0'
  gem 'factory_girl',           '~> 4.5.0'
  gem 'mocha',                  '~> 1.1.0'
  gem 'vcr',                    '~> 2.9.3'
  gem 'webmock',                '~>1.20.4'
end

group :development, :test do
  gem 'byebug',                 '~> 4.0.5'
end