require_relative 'billion_crawler'
require 'bundler'
 
namespace :debug do
  
  QUEUE_NAME = "new_urls"
  
  desc 'Add seed urls'
  task :seed do
    puts "Empty Redis..."
    $redis.flushall

    urls = ["http://www.google.com", "http://www.wikipedia.org/"]
    urls.each do |url|
      puts "Add #{url} to queue"
      Crawler::ScrapperDomain.new(host: URI.parse(url).host).add_url(url: url)
    end
  end
end

namespace :rules do
  desc "load domain blacklist and whitelist urls"
  task :load do
    puts "Loads rules from config/rules.yml"
    Rules::Parser.new.read
  end
end